# Data Wrangling:
### For Analysis such as: ANOVAS, MANOVAS, Correlation, Chi- Square, Random Forest, Regressions
### For Tableau

In [3]:
#Table of Content: 

#England and UK: 
## 1st Data Wrangle: Sepreated (total and type HazNonHaz) & Merged (Mergining Classificationa and Treatment Datasets)
## 2nd Data Wrangle: Updated (removing unwanted columns, and renaming columns)
## 3rd Data Wrangle: Reshaping

In [4]:
# Import Packages

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
pd.options.display.max_rows = None
pd.options.display.max_columns = None

pd.set_option('display.max_rows', 500)

from itertools import product

# 1st Data Wrangle

In [6]:
# devins starter code

## Import Data

In [7]:
# Datasets were wrangled in R

In [8]:
# Updated_England_Industry
# Updated_England_Management
# Updated_Uk_Industry
# Updated_Uk_Management

# *England & UK*

In [9]:
# Total (without Haz/NonHaz Split) and Type (with Haz/NonHaz Split)

# Data Wrangle - Part 1

In [10]:
# iloc -> index location (calling only the first column - column 0)

In [11]:
england_industry_df = pd.read_csv("/Users/patelca/Desktop/WozU Data Science Program /WozU Final Project/Datasets/Data Wrangled Datasets/Updated_England_Industry.1.csv").iloc[:,1:]
england_managment_df = pd.read_csv("/Users/patelca/Desktop/WozU Data Science Program /WozU Final Project/Datasets/Data Wrangled Datasets/Updated_England_Management.1.csv").iloc[:,1:]

In [12]:
uk_industry_df = pd.read_csv("/Users/patelca/Desktop/WozU Data Science Program /WozU Final Project/Datasets/Data Wrangled Datasets/Updated_UK_Industry.1.csv").iloc[:,1:]
uk_managment_df = pd.read_csv("/Users/patelca/Desktop/WozU Data Science Program /WozU Final Project/Datasets/Data Wrangled Datasets/Updated_UK_Management.1.csv").iloc[:,1:]

In [13]:
# Calling the column names of the datasets
# Take a closer look at the columns of each dataset and see if anything is repeated, missing, or not neccessary

In [14]:
england_industry_df.columns

Index(['Year', 'EWC-STAT code', 'EWC-STAT description',
       'Hazardous/Non-hazardous split', 'A', 'B', 'C10-C12', 'C13-C15', 'C16',
       'C17_C18', 'C19', 'C20-C22', 'C23', 'C24_C25', 'C26-C30', 'C31-C33',
       'D', 'E36_E37_E39', 'F', 'G-U_X_G4677', 'EP_HH',
       'Total waste generation'],
      dtype='object')

In [15]:
england_managment_df.columns

Index(['Year', 'EWC-STAT code', 'EWC-STAT description',
       'Hazardous/Non-hazardous split', 'Energy recovery', 'Incineration',
       'Recovery other than energy recovery - Except backfilling',
       'Recovery other than energy recovery - Backfilling',
       'Deposit onto or into land',
       'Land treatment and release into water bodies', 'd`'],
      dtype='object')

In [16]:
uk_industry_df.columns

Index(['Year', 'EWC-STAT code', 'EWC-STAT description',
       'Hazardous/Non-hazardous split', 'A', 'B', 'C10-C12', 'C13-C15', 'C16',
       'C17_C18', 'C19', 'C20-C22', 'C23', 'C24_C25', 'C26-C30', 'C31-C33',
       'D', 'E36_E37_E39', 'F', 'G-U_X_G4677', 'EP_HH',
       'Total waste generation'],
      dtype='object')

In [17]:
uk_managment_df.columns

Index(['Year', 'EWC-STAT code', 'EWC-STAT description',
       'Hazardous/Non-hazardous split', 'Energy recovery', 'Incineration',
       'Recovery other than energy recovery - Except backfilling',
       'Recovery other than energy recovery - Backfilling',
       'Deposit onto or into land',
       'Land treatment and release into water bodies',
       'Total waste sent to final treatment'],
      dtype='object')

# Data Wrangle -> Part 2

In [18]:
# in order to anaylize the data some things need to be changed... bc... for instance...
# loc -> location 
# calling the dataset.loc (in that df we only want where H/NH split == and != Total)

In [19]:
# Spliting Total and Haz/Non-Haz into two different dataframes of Industries Waste Gen

In [20]:
england_industry_total = england_industry_df.loc[england_industry_df['Hazardous/Non-hazardous split'] == "Total"]
england_industry_type = england_industry_df.loc[england_industry_df['Hazardous/Non-hazardous split'] != "Total"]

In [21]:
# Spliting Total and Haz/Non-Haz into two different dataframes of Industries Waste Gen

In [22]:
england_managment_total = england_managment_df.loc[england_managment_df['Hazardous/Non-hazardous split'] == "Total"]
england_managment_type = england_managment_df.loc[england_managment_df['Hazardous/Non-hazardous split'] != "Total"]

In [23]:
# Spliting Total and Haz/Non-Haz into two different dataframes of Industries Waste Gen

In [24]:
uk_industry_total = uk_industry_df.loc[uk_industry_df['Hazardous/Non-hazardous split'] == "Total"]
uk_industry_type = uk_industry_df.loc[uk_industry_df['Hazardous/Non-hazardous split'] != "Total"]

In [25]:
# Spliting Total and Haz/Non-Haz into two different dataframes of Industries Waste Gen

In [26]:
uk_managment_total = uk_managment_df.loc[uk_managment_df['Hazardous/Non-hazardous split'] == "Total"]
uk_managment_type = uk_managment_df.loc[uk_managment_df['Hazardous/Non-hazardous split'] != "Total"]

In [27]:
# double checking one of the above dataframe to see if the code above worked

In [28]:
england_managment_total

,Year,EWC-STAT code,EWC-STAT description,Hazardous/Non-hazardous split,Energy recovery,Incineration,Recovery other than energy recovery - Except backfilling,Recovery other than energy recovery - Backfilling,Deposit onto or into land,Land treatment and release into water bodies,d`
2,2010,01.1,Spent solvents,Total,0,0,8436.4869999999992,0,0,0,8436.4869999999992
5,2010,01.2,"Acid, alkaline or saline wastes",Total,0,0,893.46900000000005,0,73761.87,0,74655.338999999993
8,2010,01.3,Used oils,Total,0,0,1472.0309999999995,0,239.09897435897437,1517.6688968992646,3228.7988712582383
11,2010,"01.4, 02, 03.1",Chemical wastes,Total,0,5722,76430.701000000001,0,41482.64092307692,748,124383.34192307692
14,2010,03.2,Industrial effluent sludges,Total,0,127039,443.18718000000001,0,62225.495999999999,1653.4800000000002,191361.16318
17,2010,03.3,Sludges & liquid wastes from waste treatment,Total,111552,1157,0,0,333336.978,0,446045.978
20,2010,05,Health care & biological wastes,Total,0,120146,401.15499999999997,0,91081.54,2,211630.69500000001
23,2010,06.1,"Metallic wastes, ferrous",Total,0,0,8471005.9630000014,0,2007.08,0,8473013.0430000015
26,2010,06.2,"Metallic wastes, non-ferrous",Total,0,0,1807071.622,0,1184.6010000000001,0,1808256.223
29,2010,06.3,"Metallic wastes, mixed",Total,0,0,4627014.0140000004,0,1358.2597179487179,4748,4633120.2737179492
32,2010,07.1,Glass wastes,Total,0,0,1258655.0866190474,0,8823.36,0,1267478.4466190476
35,2010,07.2,Paper & cardboard wastes,Total,53,0,3309029.8501251573,0,1853.4117948717949,0,3310936.2619200293
38,2010,07.3,Rubber wastes,Total,89619,0,43135.040999999997,0,5686.79,0,138440.83100000001
41,2010,07.4,Plastic wastes,Total,0,0,790289.50394117646,0,48908.758794871799,0,839198.26273604832
44,2010,07.5,Wood wastes,Total,157295,0,2489410.2709999997,0,60931.619999999995,0,2707636.8909999998
47,2010,07.6,Textile wastes,Total,0,0,106542.28299999995,0,2243,0,108785.28299999995
50,2010,07.7,Waste containing PCB,Total,0,0,0,0,5.52,0,5.52
53,2010,08*,Discarded equipment,Total,0,0,222979.66200000001,0,6202.33,0,229181.992
56,2010,08.1,Discarded vehicles,Total,0,0,315927.071,0,14.2,0,315941.27100000001
59,2010,08.41,Batteries & accumulators wastes,Total,0,0,4919.1469999999999,0,92.797948717948714,0,5011.944948717949
62,2010,09.1,Animal & mixed food waste,Total,74496,446736.565,613449.30799999996,0,48047.826000000001,0,1182729.699
65,2010,09.2,Vegetal wastes,Total,0,45384,4247954.6330000004,0,139569.5,0,4432908.1330000004
68,2010,09.3,"Animal faeces, urine & manure",Total,0,307524,3988.35,0,2499.88,1643.0400000000002,315655.26999999996
71,2010,10.1,Household & similar wastes,Total,0,4027762,704270.8,0,10707229.747,477.78442263480366,15439740.331422633
74,2010,10.2,Mixed & undifferentiated materials,Total,0,148706.60499999998,281761.27200000006,0,362632.77384615387,3049,796149.65084615396
77,2010,10.3,Sorting residues,Total,204267,0,257289.8,0,10027156.552999999,0,10488713.353
80,2010,11,Common sludges,Total,0,182830,1014282.2536822407,18431.538020289834,33041.800000000003,0,1248585.5917025306
83,2010,12.1,Mineral waste from construction & demolition,Total,0,0,46109408.566951014,620493.18911165977,1821672.7100000002,0,48551574.466062672
86,2010,"12.2, 12.3, 12.5",Other mineral wastes,Total,0,0,66694.679999999993,86776.816999999995,751838.39,12612182,13517491.887
89,2010,12.4,Combustion wastes,Total,0,0,18567.294000000002,0,2217196.7319999998,0,2235764.0260000001
92,2010,12.6,Soils,Total,0,0,9856335.1073541977,9919894.4940659106,14904084.961000001,0,34680314.562420107
95,2010,12.7,Dredging spoils,Total,0,0,887.99738219895289,0,350119.34100000001,11095337.729482433,11446345.067864632
98,2010,"12.8, 13",Mineral waste from waste treatment & stabilise...,Total,6929,0,5555.4939999999997,325.113,1459311.9980000001,0,1472121.6050000002
101,2010,Total,*Total waste treated,Total,644211,5413007.1699999999,86714502.101235017,10645921.15119786,43565841.565000005,23721358.702801965,170704841.69023487
104,2012,01.1,Spent solvents,Total,0,0,31.32,0,11.58,0,42.9
107,2012,01.2,"Acid, alkaline or saline wastes",Total,0,0,944.37099999999998,0,76531.224000000002,0,77475.595000000001
110,2012,01.3,Used oils,Total,101054,1285,2531.0169999999998,0,402.56,0,105272.57699999999
113,2012,"01.4, 02, 03.1",Chemical wastes,Total,0,128680,114099.91099999999,0,28030.131000000008,0,270810.04200000002
116,2012,03.2,Industrial effluent sludges,Total,0,0,7209.1466100000007,190.55520000000001,12941.45667,0,20341.158479999998
119,2012,03.3,Sludges & liquid wastes from waste treatment,Total,0,0,373.69890000000004,67.753799999999998,91212.693299999999,0,91654.145999999993
122,2012,05,Health care & biological wastes,Total,0,106892,119.78999999999999,0,104827.69500000001,0,211839.48499999999
125,2012,06.1,"Metallic wastes, ferrous",Total,0,0,8555183.762000002,229660.92,1800.7260000000001,0,8786645.4080000017
128,2012,06.2,"Metallic wastes, non-ferrous",Total,0,5140,1511666.5899999999,2823.33,1580.81,0,1521210.73
131,2012,06.3,"Metallic wastes, mixed",Total,0,0,3885315.5700000003,0,338.42599999999999,0,3885653.9960000003
134,2012,07.1,Glass wastes,Total,0,0,1284459.5864883719,210.9,40203.053,0,1324873.5394883719
137,2012,07.2,Paper & cardboard wastes,Total,0,0,4248169.3450000007,0,4104.4160000000002,0,4252273.7610000009
140,2012,07.3,Rubber wastes,Total,118604,0,20831.021999999997,0,1837.9,0,141272.92199999999
143,2012,07.4,Plastic wastes,Total,0,0,366880.85047826089,220,115847.954,0,482948.80447826092
146,2012,07.5,Wood wastes,Total,202155,0,2155236.4740000004,62166.799999999996,19823.013999999999,0,2439381.2880000002
149,2012,07.6,Textile wastes,Total,0,0,391932.74900000001,0,3659.7750000000001,0,395592.52400000003
152,2012,07.7,Waste containing PCB,Total,0,0,5296.9010000000007,0,0,0,5296.9010000000007
155,2012,08*,Discarded equipment,Total,0,0,283078.81,0,552.05500000000006,0,283630.86499999999
158,2012,08.1,Discarded vehicles,Total,0,0,0,0,0,0,0
161,2012,08.41,Batteries & accumulators wastes,Total,0,0,78718.46100000001,0,14.24,0,78732.701000000015
164,2012,09.1,Animal & mixed food waste,Total,121445,253006,721302.25800000003,0,89510.587,0,1185263.845
167,2012,09.2,Vegetal wastes,Total,43114,0,3420307.3259999994,1014.54,99813.123999999996,0,3564248.9899999993
170,2012,09.3,"Animal faeces, urine & manure",Total,293020,0,12564.78,175.22,2668.96,0,308428.96000000002
173,2012,10.1,Household & similar wastes,Total,0,5131633,377591.56700000004,5686.3,8049620.318,0,13564531.184999999
176,2012,10.2,Mixed & undifferentiated materials,Total,64645,0,143201.45799999998,0,317986.90899999999,0,525833.36699999997
179,2012,10.3,Sorting residues,Total,274854,0,494781.26300000004,49583.47,8270344.3850000007,0,9089563.1180000007
182,2012,11,Common sludges,Total,29582,161204,751207.03788449045,3140.73,1790.326,0,946924.09388449043
185,2012,12.1,Mineral waste from construction & demolition,Total,0,0,43398523.798,658030.25,1959300.3219999999,0,46015854.369999997
188,2012,"12.2, 12.3, 12.5",Other mineral wastes,Total,0,0,11927.061000000002,150470.03999999998,755828.49099999981,11751923.5,12670149.092
191,2012,12.4,Combustion wastes,Total,0,0,10132.652000000002,371806.95500000002,3239379.3740000003,0,3621318.9810000001
194,2012,12.6,Soils,Total,0,0,9326561.5380489472,10457623.874999998,16368910.054000003,0,36153095.46704895
197,2012,12.7,Dredging spoils,Total,0,0,1477.5115183246076,4368.952879581152,189169.96335078534,10941168.871727748,11136185.299476439
200,2012,"12.8, 13",Mineral waste from waste treatment & stabilise...,Total,0,0,11150.699999999999,25327.5,1485867.6680000003,0,1522345.8680000002
203,2012,Total,*Total waste treated,Total,1248473,5787840,81592808.32592839,12022568.091879578,41333910.190320782,22693092.37172775,164678691.97985649
206,2014,01.1,Spent solvents,Total,0,0,0,0,15.5,0,15.5
209,2014,01.2,"Acid, alkaline or saline wastes",Total,0,0,1590.701,0,36543.042000000001,0,38133.743000000002
212,2014,01.3,Used oils,Total,0,0,3600.9582696616935,0,365.67,0,3966.6282696616936
215,2014,"01.4, 02, 03.1",Chemical wastes,Total,0,133662,15547.540651509626,0,22921.964,0,172131.50465150963
218,2014,03.2,Industrial effluent sludges,Total,0,0,6727.6894600000005,79.671599999999998,91564.114999999991,0,98371.476059999986
221,2014,03.3,Sludges & liquid wastes from waste treatment,Total,90827.9,0,324.5994,89.286299999999997,368041.51899999997,0,459283.30469999998
224,2014,05,Health care & biological wastes,Total,0,101484.24,14.74,0,122488.59,0,223987.57
227,2014,06.1,"Metallic wastes, ferrous",Total,0,0,8312312.3259999994,1425,23470.210999999999,0,8337207.5369999995
230,2014,06.2,"Metallic wastes, non-ferrous",Total,0,0,1659529.4580000001,0,199.52,0,1659728.9780000001
233,2014,06.3,"Metallic wastes, mixed",Total,0,0,3504729.7620000001,41.7,2713.1410000000001,0,3507484.6030000001
236,2014,07.1,Glass wastes,Total,0,0,1195327.6068181817,164.23,78705.607000000004,0,1274197.4438181818
239,2014,07.2,Paper & cardboard wastes,Total,0,0,4152293.4334157645,1.84,2742.6309999999999,0,4155037.9044157644
242,2014,07.3,Rubber wastes,Total,212401.21,0,6950.6353236448522,1.99,6417.87,0,225771.70532364483
245,2014,07.4,Plastic wastes,Total,0,0,507156.39686971746,7.33,64515.86,0,571679.58686971746
248,2014,07.5,Wood wastes,Total,213509,102030,2254783.8467411036,80096.11,22442.431,0,2672861.3877411033
251,2014,07.6,Textile wastes,Total,0,3545,90234.122023127697,0,3804.47,0,97583.592023127698
254,2014,07.7,Waste containing PCB,Total,0,0,5216.424,0,6.72,0,5223.1440000000002
257,2014,08*,Discarded equipment,Total,0,0,298209.46878802695,90.6,2430.7200000000003,0,300730.7887880269
260,2014,08.1,Discarded vehicles,Total,0,0,0,0,0,0,0
263,2014,08.41,Batteries & accumulators wastes,Total,0,0,92174.739180223754,0,155.26,0,92329.999180223749
266,2014,09.1,Animal & mixed food waste,Total,129568,233842,832871.99056325911,178.72,100536.83199999999,0,1296997.5425632589
269,2014,09.2,Vegetal wastes,Total,0,0,3519978.3401777628,16854.39,72178.438999999998,0,3609011.1691777627
272,2014,09.3,"Animal faeces, urine & manure",Total,377338,154691,13455.412,139.72999999999999,3006.0540000000001,0,548630.196
275,2014,10.1,Household & similar wastes,Total,0,6016312,433978.68194551748,7122.4589999999998,5971854.6229999997,0,12429267.763945516
278,2014,10.2,Mixed & undifferentiated materials,Total,66568,3944,191848.07584222339,5250,202098.58900000001,0,469708.6648422234
281,2014,10.3,Sorting residues,Total,99337,26847.72,510322.09400000004,50159.34,7627932.5489999996,0,8314598.7029999997
284,2014,11,Common sludges,Total,22054.43,125979,760833,5106.9359999999997,5629.19,0,919602.55599999987
287,2014,12.1,Mineral waste from construction & demolition,Total,0,0,48298265.256724834,1117793.689,2130496.344,0,51546555.289724834
290,2014,"12.2, 12.3, 12.5",Other mineral wastes,Total,0,0,14261.469000000001,74260.909,691323.52099999995,11640732.352941178,12420578.251941178
293,2014,12.4,Combustion wastes,Total,0,0,12859.868,241514.649,1714101.398,0,1968475.915
296,2014,12.6,Soils,Total,0,1180.3599999999999,10268157.591428846,17469323.071000002,19641541.769000001,0,47380202.791428849
299,2014,12.7,Dredging spoils,Total,0,0,720.22540000000004,922.24,164923.19200000001,10447101.800000001,10613667.457400002
302,2014,"12.8, 13",Mineral waste from waste treatment & stabilise...,Total,95968.24,387952,4615.88,63660.740000000005,2112216,0,2664412.86
305,2014,Total,*Total waste treated,Total,1307571.7799999998,7291469.3200000003,86968892.333023414,19134284.630899999,41287383.340999998,22087834.152941179,178077435.55786458
308,2016,01.1,Spent solvents,Total,0,25115,2,0,7602,0,32719
311,2016,01.2,"Acid, alkaline or saline wastes",Total,0,0,2634.058,0,32592.690000000002,0,35226.748
314,2016,01.3,Used oils,Total,0,3146,10796.933999999999,0,239.60000000000002,0,14182.534
317,2016,"01.4, 02, 03.1",Chemical wastes,Total,23500,0,12745.229999999998,0,71253.877000000008,0,107499.107
320,2016,03.2,Industrial effluent sludges,Total,0,91765,8474.9797199999994,159.03,53401.524000000012,0,153800.53372000001
323,2016,03.3,Sludges & liquid wastes from waste treatment,Total,2415,78680,1273.8600000000001,398.52,441672.06299999985,0,524439.44299999985
326,2016,05,Health care & biological wastes,Total,7852,88742,381,0,118319.51000000002,0,215294.51
329,2016,06.1,"Metallic wastes, ferrous",Total,0,0,7609804.0189999919,38205,135333.02900000001,0,7783342.047999992
332,2016,06.2,"Metallic wastes, non-ferrous",Total,0,0,1595845.3600000013,0,221.06000000000003,0,1596066.4200000013
335,2016,06.3,"Metallic wastes, mixed",Total,0,0,4259404.8310000086,25,544.28000000000009,0,4259974.1110000089
338,2016,07.1,Glass wastes,Total,0,0,1312009.1028181817,326,71013.981,0,1383349.0838181817
341,2016,07.2,Paper & cardboard wastes,Total,18919,0,3805298.605,0,2013.7820000000002,0,3826231.3870000001
344,2016,07.3,Rubber wastes,Total,0,111003,10621.347000000003,3586,4515.78,0,129726.12700000001
347,2016,07.4,Plastic wastes,Total,0,2348,512941.96854929579,4,47341.375000000007,0,562635.34354929579
350,2016,07.5,Wood wastes,Total,0,643845,2273464.9390000002,137073,27267.53,0,3081650.469
353,2016,07.6,Textile wastes,Total,0,0,96332.597000000038,413,1053.8800000000001,0,97799.477000000043
356,2016,07.7,Waste containing PCB,Total,0,0,34.035000000000011,0,0,0,34.035000000000011
359,2016,08*,Discarded equipment,Total,0,0,397561.55000000005,0,1756.4320000000002,0,399317.98200000002
362,2016,08.1,Discarded vehicles,Total,0,0,0,0,0,0,0
365,2016,08.41,Batteries & accumulators wastes,Total,0,0,90828.415000000139,0,28,0,90856.415000000139
368,2016,09.1,Animal & mixed food waste,Total,29775,434314,805311.28299999982,213,171423.43999999997,0,1441036.7229999998
371,2016,09.2,Vegetal wastes,Total,1698,46579,3390921.1409999952,22772,84918.601999999984,0,3546888.7429999951
374,2016,09.3,"Animal faeces, urine & manure",Total,0,517281,13628.386,96,3134.4600000000009,0,534139.84600000002
377,2016,10.1,Household & similar wastes,Total,5407157,2082604,373648.24200000003,235,4002089.5699999952,0,11865733.811999995
380,2016,10.2,Mixed & undifferentiated materials,Total,417,64911,167101.72200000001,3969,178575.33699999985,0,414974.05899999989
383,2016,10.3,Sorting residues,Total,717904,1116017,545227.70399999979,127559,8190471.84500001,0,10697179.54900001
386,2016,11,Common sludges,Total,0,123118,767284.4,21415.8,30247,0,942065.20000000007
389,2016,12.1,Mineral waste from construction & demolition,Total,0,0,52485047.975841321,502200.94099999999,2206881.2610000018,0,55194130.177841321
392,2016,"12.2, 12.3, 12.5",Other mineral wastes,Total,0,304,47596.006000000001,89204,772233.18200000026,11496858,12406195.188000001
395,2016,12.4,Combustion wastes,Total,0,0,345353.37800000008,66823,432249.88600000012,0,844426.2640000002
398,2016,12.6,Soils,Total,0,0,11246740.674888905,12001271,25873793.66999995,0,49121805.344888851
401,2016,12.7,Dredging spoils,Total,0,0,3575.0816999999997,148980.53599999999,59136.073000000011,8722261,8933952.6907000002
404,2016,"12.8, 13",Mineral waste from waste treatment & stabilise...,Total,0,0,204337.61199999996,100621,1692584.3639999998,0,1997542.9759999998
407,2016,Total,*Total waste treated,Total,6209637,5429772,92396228.437517688,13265549.827,44713909.082999952,20219119,182234215.34751764

In [29]:
# Combining two subject indentifier -> Year and EWC-STAT description -> which will make each row unique

# - They did not match on the rows that were aggregates "Total waste generated" and "Total waste managed"

# - So we removed those because they were rows that represented total's

# Line 2: double checking to see what are false

In [30]:
combine_yr_ewc = england_industry_total[['Year', 'EWC-STAT description']] == england_managment_total[['Year', 'EWC-STAT description']]
combine_yr_ewc

     Year  EWC-STAT description
2    True                  True
5    True                  True
8    True                  True
11   True                  True
14   True                  True
17   True                  True
20   True                  True
23   True                  True
26   True                  True
29   True                  True
32   True                  True
35   True                  True
38   True                  True
41   True                  True
44   True                  True
47   True                  True
50   True                  True
53   True                  True
56   True                  True
59   True                  True
62   True                  True
65   True                  True
68   True                  True
71   True                  True
74   True                  True
77   True                  True
80   True                  True
83   True                  True
86   True                  True
89   True                  True
92   True                  True
95   True                  True
98   True                  True
101  True                 False
104  True                  True
107  True                  True
110  True                  True
113  True                  True
116  True                  True
119  True                  True
122  True                  True
125  True                  True
128  True                  True
131  True                  True
134  True                  True
137  True                  True
140  True                  True
143  True                  True
146  True                  True
149  True                  True
152  True                  True
155  True                  True
158  True                  True
161  True                  True
164  True                  True
167  True                  True
170  True                  True
173  True                  True
176  True                  True
179  True                  True
182  True                  True
185  True                  True
188  True                  True
191  True                  True
194  True                  True
197  True                  True
200  True                  True
203  True                 False
206  True                  True
209  True                  True
212  True                  True
215  True                  True
218  True                  True
221  True                  True
224  True                  True
227  True                  True
230  True                  True
233  True                  True
236  True                  True
239  True                  True
242  True                  True
245  True                  True
248  True                  True
251  True                  True
254  True                  True
257  True                  True
260  True                  True
263  True                  True
266  True                  True
269  True                  True
272  True                  True
275  True                  True
278  True                  True
281  True                  True
284  True                  True
287  True                  True
290  True                  True
293  True                  True
296  True                  True
299  True                  True
302  True                  True
305  True                 False
308  True                  True
311  True                  True
314  True                  True
317  True                  True
320  True                  True
323  True                  True
326  True                  True
329  True                  True
332  True                  True
335  True                  True
338  True                  True
341  True                  True
344  True                  True
347  True                  True
350  True                  True
353  True                  True
356  True                  True
359  True                  True
362  True                  True
365  True                  True
368  True                  True
371  True                  True
374  True                  True
377  True                  True
380  True                  True
383  True                  True
386  True                  True
389  True                  True
392  True                  True
395  True                  True
398  True                  True
401  True                  True
404  True                  True
407  True                 False

In [31]:
combine_yr_ewc2 = england_industry_type[['Year', 'EWC-STAT description']] == england_managment_type[['Year', 'EWC-STAT description']]
combine_yr_ewc2

     Year  EWC-STAT description
0    True                  True
1    True                  True
3    True                  True
4    True                  True
6    True                  True
7    True                  True
9    True                  True
10   True                  True
12   True                  True
13   True                  True
15   True                  True
16   True                  True
18   True                  True
19   True                  True
21   True                  True
22   True                  True
24   True                  True
25   True                  True
27   True                  True
28   True                  True
30   True                  True
31   True                  True
33   True                  True
34   True                  True
36   True                  True
37   True                  True
39   True                  True
40   True                  True
42   True                  True
43   True                  True
45   True                  True
46   True                  True
48   True                  True
49   True                  True
51   True                  True
52   True                  True
54   True                  True
55   True                  True
57   True                  True
58   True                  True
60   True                  True
61   True                  True
63   True                  True
64   True                  True
66   True                  True
67   True                  True
69   True                  True
70   True                  True
72   True                  True
73   True                  True
75   True                  True
76   True                  True
78   True                  True
79   True                  True
81   True                  True
82   True                  True
84   True                  True
85   True                  True
87   True                  True
88   True                  True
90   True                  True
91   True                  True
93   True                  True
94   True                  True
96   True                  True
97   True                  True
99   True                 False
100  True                 False
102  True                  True
103  True                  True
105  True                  True
106  True                  True
108  True                  True
109  True                  True
111  True                  True
112  True                  True
114  True                  True
115  True                  True
117  True                  True
118  True                  True
120  True                  True
121  True                  True
123  True                  True
124  True                  True
126  True                  True
127  True                  True
129  True                  True
130  True                  True
132  True                  True
133  True                  True
135  True                  True
136  True                  True
138  True                  True
139  True                  True
141  True                  True
142  True                  True
144  True                  True
145  True                  True
147  True                  True
148  True                  True
150  True                  True
151  True                  True
153  True                  True
154  True                  True
156  True                  True
157  True                  True
159  True                  True
160  True                  True
162  True                  True
163  True                  True
165  True                  True
166  True                  True
168  True                  True
169  True                  True
171  True                  True
172  True                  True
174  True                  True
175  True                  True
177  True                  True
178  True                  True
180  True                  True
181  True                  True
183  True                  True
184  True                  True
186  True                  True
187  True                  True
189  True                  True
190  True                  True
192  True                  True
193  True                  True
195  True                  True
196  True                  True
198  True                  True
199  True                  True
201  True                 False
202  True                 False
204  True                  True
205  True                  True
207  True                  True
208  True                  True
210  True                  True
211  True                  True
213  True                  True
214  True                  True
216  True                  True
217  True                  True
219  True                  True
220  True                  True
222  True                  True
223  True                  True
225  True                  True
226  True                  True
228  True                  True
229  True                  True
231  True                  True
232  True                  True
234  True                  True
235  True                  True
237  True                  True
238  True                  True
240  True                  True
241  True                  True
243  True                  True
244  True                  True
246  True                  True
247  True                  True
249  True                  True
250  True                  True
252  True                  True
253  True                  True
255  True                  True
256  True                  True
258  True                  True
259  True                  True
261  True                  True
262  True                  True
264  True                  True
265  True                  True
267  True                  True
268  True                  True
270  True                  True
271  True                  True
273  True                  True
274  True                  True
276  True                  True
277  True                  True
279  True                  True
280  True                  True
282  True                  True
283  True                  True
285  True                  True
286  True                  True
288  True                  True
289  True                  True
291  True                  True
292  True                  True
294  True                  True
295  True                  True
297  True                  True
298  True                  True
300  True                  True
301  True                  True
303  True                 False
304  True                 False
306  True                  True
307  True                  True
309  True                  True
310  True                  True
312  True                  True
313  True                  True
315  True                  True
316  True                  True
318  True                  True
319  True                  True
321  True                  True
322  True                  True
324  True                  True
325  True                  True
327  True                  True
328  True                  True
330  True                  True
331  True                  True
333  True                  True
334  True                  True
336  True                  True
337  True                  True
339  True                  True
340  True                  True
342  True                  True
343  True                  True
345  True                  True
346  True                  True
348  True                  True
349  True                  True
351  True                  True
352  True                  True
354  True                  True
355  True                  True
357  True                  True
358  True                  True
360  True                  True
361  True                  True
363  True                  True
364  True                  True
366  True                  True
367  True                  True
369  True                  True
370  True                  True
372  True                  True
373  True                  True
375  True                  True
376  True                  True
378  True                  True
379  True                  True
381  True                  True
382  True                  True
384  True                  True
385  True                  True
387  True                  True
388  True                  True
390  True                  True
391  True                  True
393  True                  True
394  True                  True
396  True                  True
397  True                  True
399  True                  True
400  True                  True
402  True                  True
403  True                  True
405  True                 False
406  True                 False

In [32]:
combine_yr_ewc3 = uk_industry_total[['Year', 'EWC-STAT description']] == uk_managment_total[['Year', 'EWC-STAT description']]
combine_yr_ewc3

     Year  EWC-STAT description
2    True                  True
5    True                  True
8    True                  True
11   True                  True
14   True                  True
17   True                  True
20   True                  True
23   True                  True
26   True                  True
29   True                  True
32   True                  True
35   True                  True
38   True                  True
41   True                  True
44   True                  True
47   True                  True
50   True                  True
53   True                  True
56   True                  True
59   True                  True
62   True                  True
65   True                  True
68   True                  True
71   True                  True
74   True                  True
77   True                  True
80   True                  True
83   True                  True
86   True                  True
89   True                  True
92   True                  True
95   True                  True
98   True                  True
101  True                 False
104  True                  True
107  True                  True
110  True                  True
113  True                  True
116  True                  True
119  True                  True
122  True                  True
125  True                  True
128  True                  True
131  True                  True
134  True                  True
137  True                  True
140  True                  True
143  True                  True
146  True                  True
149  True                  True
152  True                  True
155  True                  True
158  True                  True
161  True                  True
164  True                  True
167  True                  True
170  True                  True
173  True                  True
176  True                  True
179  True                  True
182  True                  True
185  True                  True
188  True                  True
191  True                  True
194  True                  True
197  True                  True
200  True                  True
203  True                 False
206  True                  True
209  True                  True
212  True                  True
215  True                  True
218  True                  True
221  True                  True
224  True                  True
227  True                  True
230  True                  True
233  True                  True
236  True                  True
239  True                  True
242  True                  True
245  True                  True
248  True                  True
251  True                  True
254  True                  True
257  True                  True
260  True                  True
263  True                  True
266  True                  True
269  True                  True
272  True                  True
275  True                  True
278  True                  True
281  True                  True
284  True                  True
287  True                  True
290  True                  True
293  True                  True
296  True                  True
299  True                  True
302  True                  True
305  True                 False
308  True                  True
311  True                  True
314  True                  True
317  True                  True
320  True                  True
323  True                  True
326  True                  True
329  True                  True
332  True                  True
335  True                  True
338  True                  True
341  True                  True
344  True                  True
347  True                  True
350  True                  True
353  True                  True
356  True                  True
359  True                  True
362  True                  True
365  True                  True
368  True                  True
371  True                  True
374  True                  True
377  True                  True
380  True                  True
383  True                  True
386  True                  True
389  True                  True
392  True                  True
395  True                  True
398  True                  True
401  True                  True
404  True                  True
407  True                 False

In [33]:
combine_yr_ewc4 = uk_industry_type[['Year', 'EWC-STAT description']] == uk_managment_type[['Year', 'EWC-STAT description']]
combine_yr_ewc4

     Year  EWC-STAT description
0    True                  True
1    True                  True
3    True                  True
4    True                  True
6    True                  True
7    True                  True
9    True                  True
10   True                  True
12   True                  True
13   True                  True
15   True                  True
16   True                  True
18   True                  True
19   True                  True
21   True                  True
22   True                  True
24   True                  True
25   True                  True
27   True                  True
28   True                  True
30   True                  True
31   True                  True
33   True                  True
34   True                  True
36   True                  True
37   True                  True
39   True                  True
40   True                  True
42   True                  True
43   True                  True
45   True                  True
46   True                  True
48   True                  True
49   True                  True
51   True                  True
52   True                  True
54   True                  True
55   True                  True
57   True                  True
58   True                  True
60   True                  True
61   True                  True
63   True                  True
64   True                  True
66   True                  True
67   True                  True
69   True                  True
70   True                  True
72   True                  True
73   True                  True
75   True                  True
76   True                  True
78   True                  True
79   True                  True
81   True                  True
82   True                  True
84   True                  True
85   True                  True
87   True                  True
88   True                  True
90   True                  True
91   True                  True
93   True                  True
94   True                  True
96   True                  True
97   True                  True
99   True                 False
100  True                 False
102  True                  True
103  True                  True
105  True                  True
106  True                  True
108  True                  True
109  True                  True
111  True                  True
112  True                  True
114  True                  True
115  True                  True
117  True                  True
118  True                  True
120  True                  True
121  True                  True
123  True                  True
124  True                  True
126  True                  True
127  True                  True
129  True                  True
130  True                  True
132  True                  True
133  True                  True
135  True                  True
136  True                  True
138  True                  True
139  True                  True
141  True                  True
142  True                  True
144  True                  True
145  True                  True
147  True                  True
148  True                  True
150  True                  True
151  True                  True
153  True                  True
154  True                  True
156  True                  True
157  True                  True
159  True                  True
160  True                  True
162  True                  True
163  True                  True
165  True                  True
166  True                  True
168  True                  True
169  True                  True
171  True                  True
172  True                  True
174  True                  True
175  True                  True
177  True                  True
178  True                  True
180  True                  True
181  True                  True
183  True                  True
184  True                  True
186  True                  True
187  True                  True
189  True                  True
190  True                  True
192  True                  True
193  True                  True
195  True                  True
196  True                  True
198  True                  True
199  True                  True
201  True                 False
202  True                 False
204  True                  True
205  True                  True
207  True                  True
208  True                  True
210  True                  True
211  True                  True
213  True                  True
214  True                  True
216  True                  True
217  True                  True
219  True                  True
220  True                  True
222  True                  True
223  True                  True
225  True                  True
226  True                  True
228  True                  True
229  True                  True
231  True                  True
232  True                  True
234  True                  True
235  True                  True
237  True                  True
238  True                  True
240  True                  True
241  True                  True
243  True                  True
244  True                  True
246  True                  True
247  True                  True
249  True                  True
250  True                  True
252  True                  True
253  True                  True
255  True                  True
256  True                  True
258  True                  True
259  True                  True
261  True                  True
262  True                  True
264  True                  True
265  True                  True
267  True                  True
268  True                  True
270  True                  True
271  True                  True
273  True                  True
274  True                  True
276  True                  True
277  True                  True
279  True                  True
280  True                  True
282  True                  True
283  True                  True
285  True                  True
286  True                  True
288  True                  True
289  True                  True
291  True                  True
292  True                  True
294  True                  True
295  True                  True
297  True                  True
298  True                  True
300  True                  True
301  True                  True
303  True                 False
304  True                 False
306  True                  True
307  True                  True
309  True                  True
310  True                  True
312  True                  True
313  True                  True
315  True                  True
316  True                  True
318  True                  True
319  True                  True
321  True                  True
322  True                  True
324  True                  True
325  True                  True
327  True                  True
328  True                  True
330  True                  True
331  True                  True
333  True                  True
334  True                  True
336  True                  True
337  True                  True
339  True                  True
340  True                  True
342  True                  True
343  True                  True
345  True                  True
346  True                  True
348  True                  True
349  True                  True
351  True                  True
352  True                  True
354  True                  True
355  True                  True
357  True                  True
358  True                  True
360  True                  True
361  True                  True
363  True                  True
364  True                  True
366  True                  True
367  True                  True
369  True                  True
370  True                  True
372  True                  True
373  True                  True
375  True                  True
376  True                  True
378  True                  True
379  True                  True
381  True                  True
382  True                  True
384  True                  True
385  True                  True
387  True                  True
388  True                  True
390  True                  True
391  True                  True
393  True                  True
394  True                  True
396  True                  True
397  True                  True
399  True                  True
400  True                  True
402  True                  True
403  True                  True
405  True                 False
406  True                 False

## Results ENG: 
- the years match but the EWC-STAT do not (101, 203, 305, 407)
- calling all the False (i.e. all the total waste from different years- ) from the column EWC to see aren't the same, so we can remove before we concatinate meaning combine two worksheets.
- if == True: it would return all rows where they DO match, which would be all except 101, 203, 305, 407
- if == False: it would return all rows where they DO NOT match, which would be 101, 203, 305, 407

In [34]:
# loc-> locating

In [35]:
combine_yr_ewc.loc[combine_yr_ewc['EWC-STAT description'] == False]

     Year  EWC-STAT description
101  True                 False
203  True                 False
305  True                 False
407  True                 False

In [36]:
combine_yr_ewc2.loc[combine_yr_ewc2['EWC-STAT description'] == False]

     Year  EWC-STAT description
99   True                 False
100  True                 False
201  True                 False
202  True                 False
303  True                 False
304  True                 False
405  True                 False
406  True                 False

In [37]:
combine_yr_ewc3.loc[combine_yr_ewc3['EWC-STAT description'] == False]

     Year  EWC-STAT description
101  True                 False
203  True                 False
305  True                 False
407  True                 False

In [38]:
combine_yr_ewc4.loc[combine_yr_ewc4['EWC-STAT description'] == False]

     Year  EWC-STAT description
99   True                 False
100  True                 False
201  True                 False
202  True                 False
303  True                 False
304  True                 False
405  True                 False
406  True                 False

In [39]:
# Printing the length before we remove 'Total waste generation'

In [40]:
print(len(england_industry_total))
len(england_managment_total)

136

136

In [41]:
print(len(england_managment_type))
len(england_industry_type)

272

272

In [42]:
print(len(uk_industry_total))
len(uk_managment_total)

136

136

In [43]:
print(len(uk_industry_type))
len(uk_managment_type)

272

272

In [44]:
# Row Manipulation: Calling all the rows to remove the rows that have 'Total waste generation'
# Double Checking to make sure: Printing the length after remove 'Total waste generation'

# Row Manipulation: Calling all the rows to remove the rows that have 'Total waste treated'
# Double Checking to make sure: Printing the length after remove 'Total waste treated'

In [45]:
england_industry_total = england_industry_total.loc[england_industry_total['EWC-STAT description'] != '*Total waste generation',:]
len(england_industry_total)

132

In [46]:
england_managment_total = england_managment_total.loc[england_managment_total['EWC-STAT description'] != '*Total waste treated',:]
len(england_managment_total)

132

In [47]:
england_industry_type = england_industry_type.loc[england_industry_type['EWC-STAT description'] != '*Total waste generation',:]
len(england_industry_type)

264

In [48]:
england_managment_type = england_managment_type.loc[england_managment_type['EWC-STAT description'] != '*Total waste treated',:]
len(england_managment_type)

264

In [49]:
uk_industry_total = uk_industry_total.loc[uk_industry_total['EWC-STAT description'] != '*Total waste generation',:]
len(uk_industry_total)

132

In [50]:
uk_managment_total = uk_managment_total.loc[uk_managment_total['EWC-STAT description'] != '*Total waste treated',:]
len(uk_managment_total)

132

In [51]:
uk_industry_type = uk_industry_type.loc[uk_industry_type['EWC-STAT description'] != '*Total waste generation',:]
len(uk_industry_type)

264

In [52]:
uk_managment_type = uk_managment_type.loc[uk_managment_type['EWC-STAT description'] != '*Total waste treated',:]
len(uk_managment_type)

264

In [53]:
#### Merge Worksheets

# Above lines, we made sure Year and EWC Swat were exact same before we concatenated datasets
# Now that both tables are set to True Bouleans -> meaning removed total waste gen and treated; can combine both worksheets now that the unique subject identifier are both aligned

In [54]:
total_full = pd.concat([england_industry_total, england_managment_total], axis=1)

In [55]:
type_full = pd.concat([england_industry_type, england_managment_type], axis=1)

In [56]:
total_full_uk = pd.concat([uk_industry_total, uk_managment_total], axis=1)

In [57]:
type_full_uk = pd.concat([uk_industry_type, uk_managment_type], axis=1)

In [58]:
# Printing the length after we have mereged the datasets

In [59]:
len(total_full)

132

In [60]:
len(type_full)

264

In [61]:
len(total_full_uk)

132

In [62]:
len(type_full_uk)

264

In [63]:
# Calling the column names of the concated dataset
# Checking if both mereged corectly and have all the columns; either by .columns or .head()

In [64]:
total_full.columns

Index(['Year', 'EWC-STAT code', 'EWC-STAT description',
       'Hazardous/Non-hazardous split', 'A', 'B', 'C10-C12', 'C13-C15', 'C16',
       'C17_C18', 'C19', 'C20-C22', 'C23', 'C24_C25', 'C26-C30', 'C31-C33',
       'D', 'E36_E37_E39', 'F', 'G-U_X_G4677', 'EP_HH',
       'Total waste generation', 'Year', 'EWC-STAT code',
       'EWC-STAT description', 'Hazardous/Non-hazardous split',
       'Energy recovery', 'Incineration',
       'Recovery other than energy recovery - Except backfilling',
       'Recovery other than energy recovery - Backfilling',
       'Deposit onto or into land',
       'Land treatment and release into water bodies', 'd`'],
      dtype='object')

In [65]:
type_full.columns

Index(['Year', 'EWC-STAT code', 'EWC-STAT description',
       'Hazardous/Non-hazardous split', 'A', 'B', 'C10-C12', 'C13-C15', 'C16',
       'C17_C18', 'C19', 'C20-C22', 'C23', 'C24_C25', 'C26-C30', 'C31-C33',
       'D', 'E36_E37_E39', 'F', 'G-U_X_G4677', 'EP_HH',
       'Total waste generation', 'Year', 'EWC-STAT code',
       'EWC-STAT description', 'Hazardous/Non-hazardous split',
       'Energy recovery', 'Incineration',
       'Recovery other than energy recovery - Except backfilling',
       'Recovery other than energy recovery - Backfilling',
       'Deposit onto or into land',
       'Land treatment and release into water bodies', 'd`'],
      dtype='object')

In [66]:
total_full_uk.columns

Index(['Year', 'EWC-STAT code', 'EWC-STAT description',
       'Hazardous/Non-hazardous split', 'A', 'B', 'C10-C12', 'C13-C15', 'C16',
       'C17_C18', 'C19', 'C20-C22', 'C23', 'C24_C25', 'C26-C30', 'C31-C33',
       'D', 'E36_E37_E39', 'F', 'G-U_X_G4677', 'EP_HH',
       'Total waste generation', 'Year', 'EWC-STAT code',
       'EWC-STAT description', 'Hazardous/Non-hazardous split',
       'Energy recovery', 'Incineration',
       'Recovery other than energy recovery - Except backfilling',
       'Recovery other than energy recovery - Backfilling',
       'Deposit onto or into land',
       'Land treatment and release into water bodies',
       'Total waste sent to final treatment'],
      dtype='object')

In [67]:
type_full_uk.head()

,Year,EWC-STAT code,EWC-STAT description,Hazardous/Non-hazardous split,A,B,C10-C12,C13-C15,C16,C17_C18,C19,C20-C22,C23,C24_C25,C26-C30,C31-C33,D,E36_E37_E39,F,G-U_X_G4677,EP_HH,Total waste generation,Year,EWC-STAT code,EWC-STAT description,Hazardous/Non-hazardous split,Energy recovery,Incineration,Recovery other than energy recovery - Except backfilling,Recovery other than energy recovery - Backfilling,Deposit onto or into land,Land treatment and release into water bodies,Total waste sent to final treatment
0,2010,01.1,Spent solvents,Hazardous,0,0,84.949460377175086,25.203928515981719,45.058659743050029,2825.0664151318888,44.387391014146118,95629.608909440503,100.80269133001863,819.01638583385864,1917.6401368516108,774.24452051088565,21.471970574509989,1.4512891253133389,0,14969.237744563499,0,117258.13950301244,2010,01.1,Spent solvents,Hazardous,8581,0,8436.4869999999992,0,0,0,17017.487000000001
1,2010,01.1,Spent solvents,Non-hazardous,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,z,2010,01.1,Spent solvents,Non-hazardous,z,z,z,z,z,z,z
3,2010,01.2,"Acid, alkaline or saline wastes",Hazardous,0,0,2644.4743226227511,1.5892666699683162,14.767553508758073,6197.973549642561,6717.2483825640811,40596.861821551203,2618.8016642224352,21429.840663347066,7506.9886629570701,894.47481985331126,28.026658899350352,116.80273758014525,0,8427.7860227646815,0,97195.636126183381,2010,01.2,"Acid, alkaline or saline wastes",Hazardous,0,0,79.013999999999996,0,569.4,0,648.41399999999999
4,2010,01.2,"Acid, alkaline or saline wastes",Non-hazardous,0,0,3317.5710114636677,1.7255892771741481,14.948493639590309,6310.9308768064948,756.56013947096244,47032.859106318632,2199.5689556199331,15261.28678688404,3985.4565683863866,915.37775022787775,29.145736803357117,118.13551548226599,0,10906.979298373008,0,90850.545828753413,2010,01.2,"Acid, alkaline or saline wastes",Non-hazardous,0,0,2863.9250000000002,0,73192.47,0,76056.395000000004
6,2010,01.3,Used oils,Hazardous,31991.637710338411,8117,6775.0993747785724,61.164692899388086,103.23224401765513,3148.6178313723299,4156.5604770921364,42942.453721045713,15806.007097942909,18624.625173560333,16112.105266055161,3093.1974314469066,24973.976901330025,21.422419701255947,0,104950.65356123385,7575.3179999999993,288453.07190281467,2010,01.3,Used oils,Hazardous,7,0,6417.9993996169451,0,524.64153846153852,8520.3602204286763,15470.001158507159

In [68]:
# Exporting the file as csv

In [69]:
total_full.to_csv('England_Total_Full.csv')
type_full.to_csv('England_Type_Full.csv')
total_full_uk.to_csv('UK_Total_Full.csv')
type_full_uk.to_csv('UK_Type_Full.csv')

________

# 2nd Data Wrangle

# *UK & England*

## Load Type Data without a 'z'

- Making a list of missing value types

- Dropping "z"s from type without futher wrangle

In [70]:
missing_values = ["z"]
uk_type = pd.read_csv("/Users/patelca/Desktop/WozU Data Science Program /WozU Final Project/Datasets/Data Wrangled Datasets/UK_Type_Full.csv", na_values = missing_values)

In [71]:
uk_type.head()

,Unnamed: 0,Year,EWC-STAT code,EWC-STAT description,Hazardous/Non-hazardous split,A,B,C10-C12,C13-C15,C16,C17_C18,C19,C20-C22,C23,C24_C25,C26-C30,C31-C33,D,E36_E37_E39,F,G-U_X_G4677,EP_HH,Total waste generation,Year.1,EWC-STAT code.1,EWC-STAT description.1,Hazardous/Non-hazardous split.1,Energy recovery,Incineration,Recovery other than energy recovery - Except backfilling,Recovery other than energy recovery - Backfilling,Deposit onto or into land,Land treatment and release into water bodies,Total waste sent to final treatment
0,0,2010,01.1,Spent solvents,Hazardous,0.00000,0.0,84.949460,25.203929,45.058660,2825.066415,44.387391,95629.608909,100.802691,819.016386,1917.640137,774.244521,21.471971,1.451289,0.0,14969.237745,0.000,117258.139503,2010,01.1,Spent solvents,Hazardous,8581.0,0.0,8436.4870,0.0,0.000000,0.00000,17017.487000
1,1,2010,01.1,Spent solvents,Non-hazardous,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010,01.1,Spent solvents,Non-hazardous,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,2010,01.2,"Acid, alkaline or saline wastes",Hazardous,0.00000,0.0,2644.474323,1.589267,14.767554,6197.973550,6717.248383,40596.861822,2618.801664,21429.840663,7506.988663,894.474820,28.026659,116.802738,0.0,8427.786023,0.000,97195.636126,2010,01.2,"Acid, alkaline or saline wastes",Hazardous,0.0,0.0,79.0140,0.0,569.400000,0.00000,648.414000
3,4,2010,01.2,"Acid, alkaline or saline wastes",Non-hazardous,0.00000,0.0,3317.571011,1.725589,14.948494,6310.930877,756.560139,47032.859106,2199.568956,15261.286787,3985.456568,915.377750,29.145737,118.135515,0.0,10906.979298,0.000,90850.545829,2010,01.2,"Acid, alkaline or saline wastes",Non-hazardous,0.0,0.0,2863.9250,0.0,73192.470000,0.00000,76056.395000
4,6,2010,01.3,Used oils,Hazardous,31991.63771,8117.0,6775.099375,61.164693,103.232244,3148.617831,4156.560477,42942.453721,15806.007098,18624.625174,16112.105266,3093.197431,24973.976901,21.422420,0.0,104950.653561,7575.318,288453.071903,2010,01.3,Used oils,Hazardous,7.0,0.0,6417.9994,0.0,524.641538,8520.36022,15470.001159

In [72]:
uk_type.columns

Index(['Unnamed: 0', 'Year', 'EWC-STAT code', 'EWC-STAT description',
       'Hazardous/Non-hazardous split', 'A', 'B', 'C10-C12', 'C13-C15', 'C16',
       'C17_C18', 'C19', 'C20-C22', 'C23', 'C24_C25', 'C26-C30', 'C31-C33',
       'D', 'E36_E37_E39', 'F', 'G-U_X_G4677', 'EP_HH',
       'Total waste generation', 'Year.1', 'EWC-STAT code.1',
       'EWC-STAT description.1', 'Hazardous/Non-hazardous split.1',
       'Energy recovery', 'Incineration',
       'Recovery other than energy recovery - Except backfilling',
       'Recovery other than energy recovery - Backfilling',
       'Deposit onto or into land',
       'Land treatment and release into water bodies',
       'Total waste sent to final treatment'],
      dtype='object')

In [73]:
uk_total = pd.read_csv("/Users/patelca/Desktop/WozU Data Science Program /WozU Final Project/Datasets/Data Wrangled Datasets/UK_Total_Full.csv")

In [74]:
missing_values = ["z"]
eng_type = pd.read_csv("/Users/patelca/Desktop/WozU Data Science Program /WozU Final Project/Datasets/Data Wrangled Datasets/England_Type_Full.csv", na_values = missing_values)

In [75]:
eng_total = pd.read_csv("/Users/patelca/Desktop/WozU Data Science Program /WozU Final Project/Datasets/Data Wrangled Datasets/England_Total_Full.csv")

In [76]:
eng_total.columns

Index(['Unnamed: 0', 'Year', 'EWC-STAT code', 'EWC-STAT description',
       'Hazardous/Non-hazardous split', 'A', 'B', 'C10-C12', 'C13-C15', 'C16',
       'C17_C18', 'C19', 'C20-C22', 'C23', 'C24_C25', 'C26-C30', 'C31-C33',
       'D', 'E36_E37_E39', 'F', 'G-U_X_G4677', 'EP_HH',
       'Total waste generation', 'Year.1', 'EWC-STAT code.1',
       'EWC-STAT description.1', 'Hazardous/Non-hazardous split.1',
       'Energy recovery', 'Incineration',
       'Recovery other than energy recovery - Except backfilling',
       'Recovery other than energy recovery - Backfilling',
       'Deposit onto or into land',
       'Land treatment and release into water bodies', 'd`'],
      dtype='object')

#### Drop repeated/unwanted columns

In [77]:
uk_type1 = uk_type.drop(['Unnamed: 0', 'EWC-STAT code', 'Year.1', 'EWC-STAT code.1', 'EWC-STAT description.1', 'Hazardous/Non-hazardous split.1'], axis=1)

In [78]:
uk_type1.head(1)

,Year,EWC-STAT description,Hazardous/Non-hazardous split,A,B,C10-C12,C13-C15,C16,C17_C18,C19,C20-C22,C23,C24_C25,C26-C30,C31-C33,D,E36_E37_E39,F,G-U_X_G4677,EP_HH,Total waste generation,Energy recovery,Incineration,Recovery other than energy recovery - Except backfilling,Recovery other than energy recovery - Backfilling,Deposit onto or into land,Land treatment and release into water bodies,Total waste sent to final treatment
0,2010,Spent solvents,Hazardous,0.0,0.0,84.94946,25.203929,45.05866,2825.066415,44.387391,95629.608909,100.802691,819.016386,1917.640137,774.244521,21.471971,1.451289,0.0,14969.237745,0.0,117258.139503,8581.0,0.0,8436.487,0.0,0.0,0.0,17017.487

In [79]:
uk_total1 = uk_total.drop(['Unnamed: 0', 'EWC-STAT code', 'Year.1', 'EWC-STAT code.1', 'EWC-STAT description.1', 'Hazardous/Non-hazardous split.1'], axis=1)

In [80]:
uk_total1.head(1)

,Year,EWC-STAT description,Hazardous/Non-hazardous split,A,B,C10-C12,C13-C15,C16,C17_C18,C19,C20-C22,C23,C24_C25,C26-C30,C31-C33,D,E36_E37_E39,F,G-U_X_G4677,EP_HH,Total waste generation,Energy recovery,Incineration,Recovery other than energy recovery - Except backfilling,Recovery other than energy recovery - Backfilling,Deposit onto or into land,Land treatment and release into water bodies,Total waste sent to final treatment
0,2010,Spent solvents,Total,0.0,0.0,84.94946,25.203929,45.05866,2825.066415,44.387391,95629.608909,100.802691,819.016386,1917.640137,774.244521,21.471971,1.451289,0.0,14969.237745,0.0,117258.139503,8581.0,0.0,8436.487,0.0,0.0,0.0,17017.487

In [81]:
eng_type1 = eng_type.drop(['Unnamed: 0', 'EWC-STAT code', 'Year.1', 'EWC-STAT code.1', 'EWC-STAT description.1', 'Hazardous/Non-hazardous split.1'], axis=1)

In [82]:
eng_type1.head(1)

,Year,EWC-STAT description,Hazardous/Non-hazardous split,A,B,C10-C12,C13-C15,C16,C17_C18,C19,C20-C22,C23,C24_C25,C26-C30,C31-C33,D,E36_E37_E39,F,G-U_X_G4677,EP_HH,Total waste generation,Energy recovery,Incineration,Recovery other than energy recovery - Except backfilling,Recovery other than energy recovery - Backfilling,Deposit onto or into land,Land treatment and release into water bodies,d`
0,2010,Spent solvents,Hazardous,0.0,0.0,13.697857,9.133929,16.319214,693.591932,18.387391,39262.057248,9.554549,338.426256,355.766317,82.01455,2.012466,0.451289,0.0,1046.579003,0.0,41847.992,0.0,0.0,8436.487,0.0,0.0,0.0,8436.487

In [83]:
eng_total1 = eng_total.drop(['Unnamed: 0', 'EWC-STAT code', 'Year.1', 'EWC-STAT code.1', 'EWC-STAT description.1', 'Hazardous/Non-hazardous split.1'], axis=1)

In [84]:
eng_total1.head(1)

,Year,EWC-STAT description,Hazardous/Non-hazardous split,A,B,C10-C12,C13-C15,C16,C17_C18,C19,C20-C22,C23,C24_C25,C26-C30,C31-C33,D,E36_E37_E39,F,G-U_X_G4677,EP_HH,Total waste generation,Energy recovery,Incineration,Recovery other than energy recovery - Except backfilling,Recovery other than energy recovery - Backfilling,Deposit onto or into land,Land treatment and release into water bodies,d`
0,2010,Spent solvents,Total,0.0,0.0,13.697857,9.133929,16.319214,693.591932,18.387391,39262.057248,9.554549,338.426256,355.766317,82.01455,2.012466,0.451289,0.0,1046.579003,0.0,41847.992,0.0,0.0,8436.487,0.0,0.0,0.0,8436.487

#### Renaming the columns

In [85]:
uk_type1.rename(columns={'EWC-STAT description' : 'Waste_types', 'Hazardous/Non-hazardous split' : 'Haz_NonHaz', 'C10-C12' : 'C10_C12', 'C13-C15' : 'C13_C15', 'C20-C22' : 'C20_C22', 'C26-C30' : 'C26_C30', 'C31-C33' : 'C31_C33', 'G-U_X_G4677': 'G_U_X_G4677', 'Total waste generation' : 'Total_waste_gen', 'Energy recovery' : 'Energy_recovery', 'Recovery other than energy recovery - Except backfilling' : 'No_backfilling', 'Recovery other than energy recovery - Backfilling' : 'Backfilling', 'Deposit onto or into land' : 'Deposit_land', 'Land treatment and release into water bodies' : 'Treated_waterbodies', 'Total waste sent to final treatment' : 'Total_treatment'}, inplace=True)

In [86]:
uk_total1.rename(columns={'EWC-STAT description' : 'Waste_types', 'Hazardous/Non-hazardous split' : 'Haz_NonHaz', 'C10-C12' : 'C10_C12', 'C13-C15' : 'C13_C15', 'C20-C22' : 'C20_C22', 'C26-C30' : 'C26_C30', 'C31-C33' : 'C31_C33', 'G-U_X_G4677': 'G_U_X_G4677', 'Total waste generation' : 'Total_waste_gen', 'Energy recovery' : 'Energy_recovery', 'Recovery other than energy recovery - Except backfilling' : 'No_backfilling', 'Recovery other than energy recovery - Backfilling' : 'Backfilling', 'Deposit onto or into land' : 'Deposit_land', 'Land treatment and release into water bodies' : 'Treated_waterbodies', 'Total waste sent to final treatment' : 'Total_treatment'}, inplace=True)

In [87]:
uk_total1.columns

Index(['Year', 'Waste_types', 'Haz_NonHaz', 'A', 'B', 'C10_C12', 'C13_C15',
       'C16', 'C17_C18', 'C19', 'C20_C22', 'C23', 'C24_C25', 'C26_C30',
       'C31_C33', 'D', 'E36_E37_E39', 'F', 'G_U_X_G4677', 'EP_HH',
       'Total_waste_gen', 'Energy_recovery', 'Incineration', 'No_backfilling',
       'Backfilling', 'Deposit_land', 'Treated_waterbodies',
       'Total_treatment'],
      dtype='object')

In [88]:
eng_type1.rename(columns={'EWC-STAT description' : 'Waste_types', 'Hazardous/Non-hazardous split' : 'Haz_NonHaz', 'C10-C12' : 'C10_C12', 'C13-C15' : 'C13_C15', 'C20-C22' : 'C20_C22', 'C26-C30' : 'C26_C30', 'C31-C33' : 'C31_C33', 'G-U_X_G4677': 'G_U_X_G4677', 'Total waste generation' : 'Total_waste_gen', 'Energy recovery' : 'Energy_recovery', 'Recovery other than energy recovery - Except backfilling' : 'No_backfilling', 'Recovery other than energy recovery - Backfilling' : 'Backfilling', 'Deposit onto or into land' : 'Deposit_land', 'Land treatment and release into water bodies' : 'Treated_waterbodies', 'Total waste sent to final treatment' : 'Total_treatment'}, inplace=True)

In [89]:
eng_total1.rename(columns={'EWC-STAT description' : 'Waste_types', 'Hazardous/Non-hazardous split' : 'Haz_NonHaz', 'C10-C12' : 'C10_C12', 'C13-C15' : 'C13_C15', 'C20-C22' : 'C20_C22', 'C26-C30' : 'C26_C30', 'C31-C33' : 'C31_C33', 'G-U_X_G4677': 'G_U_X_G4677', 'Total waste generation' : 'Total_waste_gen', 'Energy recovery' : 'Energy_recovery', 'Recovery other than energy recovery - Except backfilling' : 'No_backfilling', 'Recovery other than energy recovery - Backfilling' : 'Backfilling', 'Deposit onto or into land' : 'Deposit_land', 'Land treatment and release into water bodies' : 'Treated_waterbodies', 'd`' : 'Total_treatment'}, inplace=True)

In [90]:
eng_total1.columns

Index(['Year', 'Waste_types', 'Haz_NonHaz', 'A', 'B', 'C10_C12', 'C13_C15',
       'C16', 'C17_C18', 'C19', 'C20_C22', 'C23', 'C24_C25', 'C26_C30',
       'C31_C33', 'D', 'E36_E37_E39', 'F', 'G_U_X_G4677', 'EP_HH',
       'Total_waste_gen', 'Energy_recovery', 'Incineration', 'No_backfilling',
       'Backfilling', 'Deposit_land', 'Treated_waterbodies',
       'Total_treatment'],
      dtype='object')

#### Export Datasets as csv

In [91]:
uk_total1.to_csv('UK_Total_updated.csv')
uk_type1.to_csv('UK_Type_updated.csv')
eng_total1.to_csv('Eng_Total_updated.csv')
eng_type1.to_csv('Eng_Type_updated.csv')

_____

# 3rd Data Wrangle

### Data Wrangling for all ANOVAs -> Reshaping the data by using melt function 

Devin's: reshaped_location = pd.melt(total_full.drop("EWC-STAT code", axis=1), id_vars=['Year','EWC-STAT description'], value_vars=total_full.iloc[:,3:20].columns,var_name = "Location_Type", value_name="Weight")

Meredith's: MeltedUKTotal1 = pd.melt(UK_Total_updated, id_vars = ['Year', 'Waste_types'], value_vars = ['A', 'B', 'C10_C12', 'C16'])

- This is to be able to find the ANOVAs of the different A,  B, C (classifications) columns. You will need to add all your other columns in

##### England:

In [92]:
# Reshaping England Location(classification) by using melt() function

In [93]:
reshaped_location_eng = pd.melt(eng_total1, id_vars=['Year','Waste_types'], value_vars=eng_total1.iloc[:,3:20].columns, var_name = "Location_Type", value_name="Weight")

In [94]:
# Export file as csv

In [95]:
reshaped_location_eng.to_csv("Reshaped_Location.csv", index=False)

In [96]:
# Reshaping England Treatment methods by using melt() function

In [97]:
reshaped_treatment_eng = pd.melt(eng_total1, id_vars=['Year','Waste_types'], value_vars=eng_total1.iloc[:,21:-1].columns,
       var_name = "Treatment_Type", value_name="Weight")

In [98]:
# Export file as csv

In [99]:
reshaped_treatment_eng.to_csv("Reshaped_Treatment.csv", index=False)

In [100]:
# Grouping groupby() of waste and treatment by aggregate sum() function

In [101]:
total_waste_and_treatment_by_type_eng = eng_total1[["Waste_types", "Total_waste_gen", 
                                       "Total_treatment"]].groupby("Waste_types").sum().reset_index()

In [102]:
# Export file as csv

In [103]:
total_waste_and_treatment_by_type_eng.to_csv("total_waste_and_treatment_by_type_Eng.csv", index=False)

##### UK:

In [104]:
# Reshaping UK Location (classifications) by using melt() function

In [105]:
reshaped_location_uk = pd.melt(uk_total1, id_vars=['Year', 'Waste_types'], value_vars=uk_total1.iloc[:,3:20].columns, var_name = "Location_Type", value_name="Weight")

In [106]:
# Export file as csv

In [107]:
reshaped_location_uk.to_csv("UK_Reshaped_Location.csv", index=False)

In [108]:
# Reshaping UK Treatment methods by using melt() function

In [109]:
reshaped_treatment_uk = pd.melt(uk_total1, id_vars=['Year', 'Waste_types'], value_vars=uk_total1.iloc[:,21:-1].columns,
        var_name = "Location_Type", value_name="Weight")

In [110]:
# Export file as csv

In [111]:
reshaped_treatment_uk.to_csv("UK_Reshaped_Treatment.csv", index=False)

In [112]:
# Grouping groupby() of waste and treatment by aggregate sum() function

In [113]:
total_waste_and_treatment_by_type_eng = uk_total1[["Waste_types", "Total_waste_gen", 
                                       "Total_treatment"]].groupby("Waste_types").sum().reset_index()

In [114]:
# Export file as csv

In [115]:
total_waste_and_treatment_by_type_eng.to_csv("total_waste_and_treatment_by_type_UK.csv", index=False)

##### Combining 2 countires & Reshaping -> UK&England

In [116]:
uk_total1.columns

Index(['Year', 'Waste_types', 'Haz_NonHaz', 'A', 'B', 'C10_C12', 'C13_C15',
       'C16', 'C17_C18', 'C19', 'C20_C22', 'C23', 'C24_C25', 'C26_C30',
       'C31_C33', 'D', 'E36_E37_E39', 'F', 'G_U_X_G4677', 'EP_HH',
       'Total_waste_gen', 'Energy_recovery', 'Incineration', 'No_backfilling',
       'Backfilling', 'Deposit_land', 'Treated_waterbodies',
       'Total_treatment'],
      dtype='object')

In [117]:
eng_total11 = eng_total1.drop(['Total_waste_gen', 'Total_treatment'], axis=1)

In [118]:
uk_total11 = uk_total1.drop(['Year', 'Waste_types', 'Haz_NonHaz', 'Total_waste_gen', 'Total_treatment'], axis=1)

In [119]:
# Merging both countires eng and uk datasets

In [120]:
countries = pd.concat([eng_total11, uk_total11], axis=1)

In [121]:
countries.columns

Index(['Year', 'Waste_types', 'Haz_NonHaz', 'A', 'B', 'C10_C12', 'C13_C15',
       'C16', 'C17_C18', 'C19', 'C20_C22', 'C23', 'C24_C25', 'C26_C30',
       'C31_C33', 'D', 'E36_E37_E39', 'F', 'G_U_X_G4677', 'EP_HH',
       'Energy_recovery', 'Incineration', 'No_backfilling', 'Backfilling',
       'Deposit_land', 'Treated_waterbodies', 'A', 'B', 'C10_C12', 'C13_C15',
       'C16', 'C17_C18', 'C19', 'C20_C22', 'C23', 'C24_C25', 'C26_C30',
       'C31_C33', 'D', 'E36_E37_E39', 'F', 'G_U_X_G4677', 'EP_HH',
       'Energy_recovery', 'Incineration', 'No_backfilling', 'Backfilling',
       'Deposit_land', 'Treated_waterbodies'],
      dtype='object')

In [122]:
# Reshaping by using melt() function

In [123]:
reshaped_Countries = pd.melt(countries.drop('Haz_NonHaz', axis=1), id_vars=['Year','Waste_types'], value_vars=countries.iloc[:,3:-1].columns,
       var_name = "Location&Treatment_Type", value_name="Weight")

In [124]:
# Export file as csv

In [125]:
reshaped_Countries.to_csv("Reshaped_Countries.csv", index=False)